FROM python:3.8
# COPY /app /app
COPY pyproject.toml .
COPY alembic.ini .
COPY wsgi.py .
# COPY tests /tests/
#WORKDIR /app
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

# Run the application
ENTRYPOINT ["gunicorn", "-b", "0.0.0.0:8081", "wsgi:app"]