version: "3.9"

#secrets:
#  # Secrets are single-line text files where the sole content is the secret
#  # Paths in this example assume that secrets are kept in local folder called ".secrets"
#  POSTGRES_PASSWORD:
#    file: .secrets/db_root_pwd.txt
#  POSTGRES_USER:
#    file: .secrets/db_user.txt
#

services:
  api:
    image: cyrzolotarev/api-movie-library
    env_file:
      - .env
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    ports:
      - 8081:8081

    restart: always
    volumes:
      - /opt/data/{APP_NAME}/app:/data

  db:
    image: postgres:13.2
    restart: always
    container_name: db-${APP_NAME}
    hostname: db-${APP_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      -  /opt/data/{APP_NAME}/db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 25
