version: "3.9"

services:
  api:
    image: cyrzolotarev/api-movie-library
    env_file:
      - .env
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    depends_on:
      db:
        condition: service_healthy

    ports:
      - 8081:8081

    restart: always
    volumes:
      - /opt/data/${APP_NAME}/app:/data

    links:
      - db:pgsql-server

  db:
    image: postgres:13.2
    restart: always
    container_name: db-${APP_NAME}
    hostname: db-${APP_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      -  /opt/data/${APP_NAME}/db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 25

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    external_links:
      - "api-movie-library:api-movie-library"
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - /opt/etc/nginx/conf:/etc/nginx
